export const PaletteGenerator = {
    generatePalette: () => {
      const colors = [];
      for (let i = 0; i < 5; i++) {
        const hue = Math.floor(Math.random() * 360);
        const saturation = Math.floor(Math.random() * 30) + 70;
        const lightness = Math.floor(Math.random() * 30) + 35;
        colors.push(`hsl(${hue}, ${saturation}%, ${lightness}%)`);
      }
      return colors;
    }
  };
  //he purpose of this function is to generate a palette of 5 random colors in the HSL (Hue, Saturation, Lightness) color model.
  //The function starts by initializing an empty array called colors.
  //It then enters a for loop that runs 5 times, each time generating a random hue, saturation, and lightness value.
  //The hue is generated by Math.floor(Math.random() * 360), which returns a random
  // integer between 0 and 360, representing the hue in the HSL color model.
  //The saturation and lightness are generated by Math.floor(Math.random() * 30) + 70 and Math.floor(Math.random() * 30) + 35, respectively.
  //These values are then used to generate a random color in the HSL color model using the hsl(hue, saturation, lightness) function.
  //The resulting color is then pushed into the colors array.
  //Finally, the function returns the colors array, which contains 5 random colors in the HSL color model.
  

